name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/${{ https://github.com/bedashto/Phishing-Detection-Tool-With-ML }} repo
        cd repo

    - name: Use system Python
      run: python --version

    - name: Install dependencies
      run: |
        cd repo
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd repo
        python -m unittest discover -s . -p "test_*.py"
